### ISSUE TITLE
False comission

### ISSUE THREAD

**Issue by Kocojambo** [eugenioclrc/binance-crypto-triangular-arbitrage#2]
Hi, default comission 0.0075% doesn't exist on binance, even with BNB, only 0.075%. Is that possible to change that?

**Comment by digitalftl** [comment]
Yes, download the project, use the search in folder function, look for 0.0075 and replace it with your desired fee.

> src\App.svelte - Line 206
> src\lib\profit.js - Line 5

**Comment by eugenioclrc** [comment]
Will fix it soon, i will become more active in this proyect

**Comment by eugenioclrc** [comment]
Solved
