### ISSUE TITLE
Comission

### ISSUE THREAD

**Issue by Kocojambo** [eugenioclrc/binance-crypto-triangular-arbitrage#3]
Hi, default comission 0.0075% doesn't exist on binance, even with BNB, only 0.075%. Is that possible to change that?

**Comment by robertsmaoui** [comment]
> Hi, default comission 0.0075% doesn't exist on binance, even with BNB, only 0.075%. Is that possible to change that?

exactly !! and the fee must be multiplied by 3 (3 transactions), then results in the demo not real !!

**Comment by eugenioclrc** [comment]
Boys, please chill, was a mistake. Will fix it soon.
https://www.binance.com/en/fee/schedule

Feel free to collaborate with a pull request

![Captura de pantalla de 2021-12-04 14-40-27](https://user-images.githubusercontent.com/332426/144719192-6a453fc1-d8e0-40d1-a684-ebd1df0e7680.png)

**Comment by eugenioclrc** [comment]
Solved
