### ISSUE TITLE
Live trade

### ISSUE THREAD

**Issue by SparkySparkman** [eugenioclrc/binance-crypto-triangular-arbitrage#5]
Hello Sir,

This script of yours looks very good. Keep up the good work :100: 

You gave these couple of days ago :
exchange.createOrder(target.symbol, 'limit', 'buy', amount, target.ask),
exchange.createOrder(target.symbol, 'limit', 'sell', amount, target.bid)

But where do I put my Binance API keys and in what kind of format ?
And How do I use them by making live order ?

Is it possible for you to update script with a possibility to make live orders ?

Also, is it possible to change script that it only looks for trade opportunities starting from, and ending to USDT, for example USDT → ANY → BTC → USDT ?
Or is it doing this already ?

That way one only needs to have USDT in their Binance account

Or is it possible to set it to follow only certain coins ?

There is const stables in profit.js file but I don't know what it means.

Trade logging would be very nice addition too, indeed

Thank you in advance :+1:

**Comment by aknkaplanoglu** [comment]
Is there any update for this thread? But where do I put my Binance API keys and in what kind of format ?

Thanks

**Comment by francythepseud** [comment]
Hi guys, don't be fooled, by now there are no triangular arbitrage opportunities on the same exchange, and if there are, we need a very fast machine to make the transaction, so they are decoy, do not be fooled, if there was a possibility of do you think he would have put it online for everyone? but please ....

**Comment by SparkySparkman** [comment]
@francythepseud It's not true
