### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by am5188** [eugenioclrc/binance-crypto-triangular-arbitrage#9]
How do I deploy to github and get it running?

**Comment by eugenioclrc** [comment]
You will have to rebuild the algorith in node and use cctx to interact with the exchange

**Comment by am5188** [comment]
Can you provide a tutorial?

**Comment by eugenioclrc** [comment]
No, but check out this;
https://github.com/ccxt/ccxt

**Comment by am5188** [comment]
thanks a lot
